const express = require("express");
const path = require("path");

// import the document scanner backend (express app)
const docScanApp = require("./doc-scan/src/server");

const app = express();
const PORT = process.env.PORT || 3001;

// JSON body parsing for our own endpoints (if we add any later).
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Mount the document scanner routes and frontend under /doc-scan
// This includes all /api endpoints as well as the static front-end served
// by the scanner application itself.
app.use("/doc-scan", docScanApp);

// Serve React production build (generated by `npm run build`)
const reactDist = path.join(__dirname, "dist");
app.use(express.static(reactDist));

// For any unhandled request (that isn't for static assets or /doc-scan/*),
// serve the React app. This allows client-side routing to work.
app.get("*", (req, res) => {
  res.sendFile(path.join(reactDist, "index.html"));
});

app.listen(PORT, () => {
  console.log(`Root server listening on http://localhost:${PORT}`);
  console.log("- React app at http://localhost:${PORT}/");
  console.log(
    "- Document scanner UI/API at http://localhost:${PORT}/doc-scan/",
  );
});
