export default function AIInsights({ insight }) {
  return (
    <div style={card}>
      <h2 style={title}>AI Insights</h2>

      <p style={text}>
        {insight || "Loading AI security analysis..."}
      </p>

      <p style={footer}>
        Generated by GuardLY AI engine
      </p>
    </div>
  );
}

const card = {
  background: "rgba(20,33,61,0.6)",
  borderRadius: "16px",
  padding: "20px",
};

const title = { marginBottom: "10px" };

const text = {
  color: "#d1d5db",
  lineHeight: "1.6",
};

const footer = {
  marginTop: "10px",
  fontSize: "12px",
  color: "#6b7280",
};